### ISSUE TITLE
About the output of hotdog plate

### ISSUE THREAD

**Issue by Epsilon404** [ashmrz/LaTeRF#1]
Hi, I tried to train LaTeRF on the sample scene of hotdog by `python DS_NeRF/run_nerf.py --config DS_NeRF/configs/hotdog.txt`, but the output is not as good as the result of the paper. 
![image](https://user-images.githubusercontent.com/94212652/203051889-1e3cca2e-ccc8-469a-9bc9-b5d4385f3d23.png)
Here is the defult config file `hotdog.txt`:
```
expname = hotdog_test
basedir = ./logs
datadir = ./data/hotdog
dataset_type = blender

no_batching = False
use_viewdirs = True

white_bkgd = False

N_samples = 64
N_importance = 64
N_rand = 1024

precrop_iters = 500
precrop_frac = 0.5

half_res = True

text_query = "A plain empty plate"

lrate = 0.01
lrate_decay = 10
render_factor = 4

clip_weight = 0.01
clf_reg_weight = 0
```
So I'm wondering how to modify the config file `/LaTeRF/DS_NeRF/configs/hotdog.txt` can make it output the result the same as the paper.
Thanks!

**Comment by ashmrz** [comment]
Hi! 

Thank you for your interest in our work. I suggest increasing the clip weight. However, the results in the paper where obtained with the use of original NeRF rather than Instant-NGP+DS-NeRF, that used to take around 10 hours for each scene. Now, the implementation is much faster, but not tested on all of the scenes. Moreover, if you are interested, I suggest adding the augmentations from [DiffAugment](https://github.com/mit-han-lab/data-efficient-gans) as in [Understanding Pure CLIP Guidance for Voxel Grid NeRF Models](https://arxiv.org/abs/2209.15172) to the rendered images in `DS_NeRF/run_nerf.py`, before passing them to the CLIP model, to make the training more consistent.
